### PR TITLE
Add Missing Textdomain

### PR DESCRIPTION
**Pull request by quasel**

### CODE REVIEW

**Comment by judgej** [comment]
Thanks. I'll put that text domain string into a constant at some point too, just in case it ever needs to be changed (though not wanting to break any translations, obviously).

**Comment by quasel** [comment]
text domain should be a string - nothing else ;) 
https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Comment by judgej** [comment]
Sure, but defining that string in one place, rather than lots of places, is a bit more DRY. But it's not a show-stopper.

**Comment by quasel** [comment]
The link explains the reason ;) althoug you'r right it's against DRY :+1:

**Comment by judgej** [comment]
Ah, gotcha. Great for runtime; rubbish for translating. So a string it will remain.

**Pull request merged**
